/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData search_2_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1_ = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1_ = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_1 = IconData(0xec44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
